const actionTypes = Object.freeze({
    SET_TASKS: 'SET_TASKS',
    TOGGLE_CHECK_REMOVE_TASKS: 'TOGGLE_CHECK_REMOVE_TASKS',
    TOGGLE_LOADED: 'TOGGLE_LOADED',
    DELETE_ONE_TASK: 'DELETE_ONE_TASK',
    ADD_TASK: 'ADD_TASK',
    EDIT_TASK: 'EDIT_TASK',
    REMOVE_SOME_TASKS: 'REMOVE_SOME_TASKS',
    TOGGLE_CHECK_ALL_SELECTED: 'TOGGLE_CHECK_ALL_SELECTED',
    TOGGLE_OPEN_ADD_MODAL: 'TOGGLE_OPEN_ADD_MODAL',
    OPEN_MODAL_FOR_SELECTED: 'OPEN_MODAL_FOR_SELECTED',
    OPEN_MODAL_FOR_ALL: 'OPEN_MODAL_FOR_ALL',
    HANDLE_EDIT_TASK: 'HANDLE_EDIT_TASK',
    EDIT_TASK_SET_NULL: 'EDIT_TASK_SET_NULL',
    SET_SUCCESS_MESSAGE: 'SET_SUCCESS_MESSAGE',
    SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
    SINGLE_TASK_EDITED_TASK: 'SINGLE_TASK_EDITED_TASK',
    LOADING_TURN_OFF_ON: 'LOADING_TURN_OFF_ON',
    ERROR_TURN_OFF_ON: 'ERROR_TURN_OFF_ON',
    SET_SINGLE_TASK: 'SET_SINGLE_TASK',
    TOGGLE_TASK_STATUS: 'TOGGLE_TASK_STATUS'

})
export default actionTypes